import { GoogleGenerativeAI } from "@google/generative-ai";
import {
  buildGeminiPrompt,
  validateAiAnalysis,
} from './aiValidation';

const apiKey = import.meta.env.VITE_GEMINI_API_KEY;

export async function analyzeTextWithGemini(text, contextLang = 'en') {
  if (!apiKey || apiKey.includes("YOUR_") || apiKey.length < 10) {
    console.warn("⚠️ [Gemini AI] API key is missing or invalid in .env (VITE_GEMINI_API_KEY). Skipping AI analysis.");
    return null;
  }

  const genAI = new GoogleGenerativeAI(apiKey);

  const prompt = buildGeminiPrompt(text, contextLang);

  // Attempt models in sequence, prioritizing the highest requested flash versions
  const modelsToTry = ["gemini-1.5-flash", "gemini-1.5-pro"];
  
  for (const modelName of modelsToTry) {
    try {
      console.log(`🤖 [Gemini AI] Calling model ${modelName}...`);
      const model = genAI.getGenerativeModel({ 
        model: modelName,
        generationConfig: {
          responseMimeType: "application/json",
          temperature: 0
        }
      });
      const result = await Promise.race([
        model.generateContent(prompt),
        new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), 15000))
      ]);
      const response = await result.response;
      let textResponse = response.text();
      
      // Fallback cleanup just in case older models ignore the mimeType
      textResponse = textResponse.replace(/```json/gi, '').replace(/```/g, '').trim();
      const parsedData = JSON.parse(textResponse);
      const validatedData = validateAiAnalysis(parsedData, text, contextLang);
      if (!validatedData) {
        console.warn(`[Gemini AI] ${modelName} returned an invalid or ungrounded response.`);
        continue;
      }
      console.log(`✅ [Gemini AI] Response successfully generated by ${modelName}`);
      return validatedData;
    } catch (error) {
      console.warn(`⚠️ [Gemini AI] Model ${modelName} call failed:`, error?.message || error);
    }
  }

  return null;
}

