export const LESSON_CARDS = [
  // --- Category 1: Courier & Delivery ---
  {
    id: 101,
    title: "Pos Malaysia / Courier COD Tax SMS",
    title_ms: "SMS Cukai COD Pos Malaysia / Kurier",
    category: "Courier & Delivery",
    isDailyFeatured: true,
    summary: "SMS claiming a parcel is held at sorting hub unless a small RM2.50 tax fee is paid within 30 minutes.",
    summary_ms: "SMS mendakwa bungkusan ditahan di pusat isihan melainkan cukai kecil RM2.50 dibayar dalam 30 minit.",
    exampleMessage: "POS MALAYSIA: Parcel MY8492040 held at sorting hub. Pay RM2.50 processing fee within 30 mins to avoid item disposal: pos-laju.info/claim-fee/2.50",
    psychology: "Creates artificial urgency with a trivial small amount (RM2.50) so victims enter credit card details without double-checking.",
    psychology_ms: "Mencipta kecemasan buatan dengan jumlah kecil (RM2.50) supaya mangsa memasukkan butiran kad kredit tanpa semakan.",
    redFlags: ["Shortened / fake domain (pos-laju.info instead of pos.com.my)", "30-minute countdown pressure", "Unrequested parcel tracking code"],
    redFlags_ms: ["Domain palsu (pos-laju.info bukan pos.com.my)", "Tekanan masa 30 minit", "Kod penjejakan bungkusan tidak diminta"],
    advisory: "POS Malaysia will never request payment details via SMS, WhatsApp, or unofficial links. Always use the official Pos Malaysia app or portal.",
    advisory_ms: "POS Malaysia tidak akan meminta butiran pembayaran melalui SMS atau pautan tidak rasmi. Sentiasa gunakan portal rasmi."
  },
  {
    id: 102,
    title: "NinjaVan Fake COD Cash Overcharge",
    title_ms: "Caj Berlebihan Tunai COD Palsu NinjaVan",
    category: "Courier & Delivery",
    isDailyFeatured: false,
    summary: "Scammer delivers cheap worthless items (e.g. plastic beads) to victims' homes demanding RM150 Cash-On-Delivery.",
    summary_ms: "Scammer menghantar barang murah (cth. manik plastik) ke rumah mangsa dan meminta RM150 Tunai Semasa Penghantaran.",
    exampleMessage: "NinjaVan Notification: Rider on the way to deliver parcel #NV9912. Cash amount due upon arrival: RM149.90. Prepare exact cash.",
    psychology: "Targets elderly family members staying home who assume their working children ordered something online.",
    psychology_ms: "Menyasar ahli keluarga warga emas di rumah yang menganggap anak mereka memesan barang secara dalam talian.",
    redFlags: ["Unannounced COD package", "Rider refuses to let recipient inspect parcel contents before paying cash", "No purchase history in e-commerce apps"],
    redFlags_ms: ["Pakej COD tidak diumumkan", "Penghantar enggan membenarkan penerima memeriksa kandungan sebelum membayar", "Tiada rekod pembelian"],
    advisory: "Advise family members to never accept unannounced COD parcels without calling the purchaser first to verify.",
    advisory_ms: "Nasihatkan ahli keluarga supaya jangan menerima bungkusan COD tanpa menelefon pembeli terlebih dahulu."
  },
  {
    id: 103,
    title: "DHL Customs Clearance Tax Phishing Email",
    title_ms: "E-mel Pancingan Data Cukai Kastam DHL",
    category: "Courier & Delivery",
    isDailyFeatured: false,
    summary: "Phishing email claiming an international shipment requires clearance tax payment before release.",
    summary_ms: "E-mel mendakwa penghantaran antarabangsa memerlukan pembayaran cukai pelepasan kastam sebelum dilepaskan.",
    exampleMessage: "DHL Express: Your shipment #9410291 is pending customs clearance. A mandatory RM45.00 duty fee is required: dhl-customs-my.net/pay",
    psychology: "Impersonates international courier brands to panic online shoppers waiting for overseas imports.",
    psychology_ms: "Menyamar sebagai jenama kurier antarabangsa untuk menakutkan pembeli dalam talian yang menunggu barangan.",
    redFlags: ["Non-official email domain (e.g. notice@dhl-customs-my.net)", "Direct link to payment form requesting card CVV"],
    redFlags_ms: ["Domain e-mel tidak rasmi", "Pautan terus ke borang pembayaran yang meminta CVV kad"],
    advisory: "Verify shipment status directly on the official dhl.com portal using your master tracking number.",
    advisory_ms: "Sahkan status penghantaran secara terus di portal rasmi dhl.com menggunakan nombor penjejakan anda."
  },

  // --- Category 2: Job & Task Scams ---
  {
    id: 201,
    title: "Shopee/Lazada Cart Click Commission Scam",
    title_ms: "Scam Komisen Klik Troli Shopee/Lazada",
    category: "Job & Task Scams",
    isDailyFeatured: true,
    summary: "Promises RM300-RM800 daily for processing e-commerce orders, requiring advancing personal funds for task deposits.",
    summary_ms: "Menjanjikan RM300-RM800 sehari untuk memproses pesanan, memerlukan pendahuluan wang peribadi untuk deposit tugasan.",
    exampleMessage: "Shopee HR: Earn RM500/day working 1 hr daily! Task 1: Deposit RM100 to unlock order #1 and receive RM150 commission instantly.",
    psychology: "Pays out small initial commissions to build trust, then demands thousands of Ringgit in deposit top-ups to 'unlock' stuck payouts.",
    psychology_ms: "Membayar komisen awal kecil untuk membina kepercayaan, kemudian meminta ribuan Ringgit deposit untuk membuka bayaran.",
    redFlags: ["Hired via unsolicited Telegram/WhatsApp messages", "Requires depositing money to unlock work tasks", "Payments routed to personal bank accounts"],
    redFlags_ms: ["Ditawar kerja melalui Telegram/WhatsApp", "Perlu wang pendahuluan untuk tugasan", "Bayaran ke akaun bank peribadi individu"],
    advisory: "Legitimate e-commerce platforms do not hire workers via Telegram or require advance cash deposits to perform job duties.",
    advisory_ms: "Platform e-dagang yang sah tidak mengupah pekerja melalui Telegram atau meminta deposit wang tunai."
  },
  {
    id: 202,
    title: "TikTok / YouTube Video Like Payout Scam",
    title_ms: "Scam Bayaran Like Video TikTok / YouTube",
    category: "Job & Task Scams",
    isDailyFeatured: false,
    summary: "Earn RM5 per video like, then forced into high-tier crypto trading groups to retrieve accumulated earnings.",
    summary_ms: "Dapat RM5 setiap 'like' video, kemudian dipaksa masuk ke kumpulan perdagangan kripto untuk mendapatkan pendapatan.",
    exampleMessage: "Digital Media Marketing: Get paid RM5 for every TikTok video liked! Complete 10 likes to earn RM50. Join VIP Telegram: t.me/media_tasks_my",
    psychology: "Lures victims with fun, effortless tasks before switching to mandatory crypto deposit traps.",
    psychology_ms: "Memikat mangsa dengan tugasan mudah sebelum bertukar kepada perangkap deposit kripto wajib.",
    redFlags: ["Unrealistic compensation for simple clicks", "Task payouts locked behind Telegram crypto investments"],
    redFlags_ms: ["Pampasan tidak realistik untuk tugasan klik mudah", "Pembayaran dikunci di sebalik pelaburan kripto Telegram"],
    advisory: "Never transfer money to unverified Telegram administrators to release promised task earnings.",
    advisory_ms: "Jangan sekali-kali memindahkan wang kepada pentadbir Telegram untuk melepaskan pendapatan yang dijanjikan."
  },
  {
    id: 203,
    title: "Hotel Rating & Booking Agent Task Scam",
    title_ms: "Scam Tugasan Penilaian & Ejen Tempahan Hotel",
    category: "Job & Task Scams",
    isDailyFeatured: false,
    summary: "Claims travel agencies pay users to write fake 5-star Google/Agoda reviews, requiring prepaid security deposits.",
    summary_ms: "Mendakwa agensi pelancongan membayar pengguna untuk menulis ulasan 5-bintang palsu, memerlukan deposit pendahuluan.",
    exampleMessage: "Agoda Marketing Agent: Review 5 hotels in KL & get RM250 daily. Security deposit RM200 required to activate reviewer badge.",
    psychology: "Exploits brand names of reputable travel companies to make fake job offers appear legitimate.",
    psychology_ms: "Mengeksploitasi nama jenama syarikat pelancongan terkenal untuk menjadikan tawaran kerja palsu kelihatan sah.",
    redFlags: ["No official interview", "Requires safety deposit fee"],
    redFlags_ms: ["Tiada temuduga rasmi", "Memerlukan bayaran deposit keselamatan"],
    advisory: "Agoda and Google do not hire freelance reviewers via WhatsApp or charge reviewer security deposits.",
    advisory_ms: "Agoda dan Google tidak pernah mengupah pengulas bebas melalui WhatsApp atau mengenakan deposit."
  },

  // --- Category 3: Threat & Govt Impersonation ---
  {
    id: 301,
    title: "LHDN Tax Audit Penalty & Arrest Warrant SMS",
    title_ms: "SMS Penalti LHDN & Waran Tangkap",
    category: "Threat & Govt Impersonation",
    isDailyFeatured: true,
    summary: "Threatens an unpaid RM50,000 tax penalty, bank account freeze, and arrest warrant unless settled within 2 hours.",
    summary_ms: "Mengancam penalti cukai RM50,000, pembekuan akaun bank, dan waran tangkap kecuali diselesaikan dalam masa 2 jam.",
    exampleMessage: "LHDN AMARAN: Saman Cukai RM50,000 belum dibayar. Akaun bank anda akan dibekukan & waran tangkap dikeluarkan dalam 2 jam: lhdn-cukai-portal.org",
    psychology: "Exploits fear of law enforcement and legal consequences to induce panic and force instant payments.",
    psychology_ms: "Mengeksploitasi ketakutan terhadap penguatkuasaan undang-undang untuk mencetuskan panik dan memaksa pembayaran.",
    redFlags: ["Short deadline threat (within 2 hours)", "Redirects to non-government portal (lhdn-cukai-portal.org instead of hasil.gov.my)", "Demands payment to personal lawyer account"],
    redFlags_ms: ["Ancaman tarikh akhir pendek (dalam masa 2 jam)", "Pautan portal tidak rasmi (bukan .gov.my)", "Minta bayaran ke akaun peribadi peguam"],
    advisory: "Government tax agencies never send threats of immediate arrest via SMS links or demand payment to personal accounts.",
    advisory_ms: "Agensi cukai kerajaan tidak pernah menghantar ancaman tangkapan segera melalui SMS atau meminta bayaran ke akaun peribadi."
  },
  {
    id: 302,
    title: "PDRM / Court Macao Phone Call Scam",
    title_ms: "Panggilan Penipuan Macao PDRM / Mahkamah",
    category: "Threat & Govt Impersonation",
    isDailyFeatured: false,
    summary: "Scammers spoofing police station hotline numbers claiming your IC is implicated in drug trafficking or money laundering.",
    summary_ms: "Scammer memalsukan nombor talian polis mendakwa IC anda terlibat dalam pengedaran dadah atau pengubahan wang haram.",
    exampleMessage: "Call from IPK Sabah: 'No Kad Pengenalan anda dikesan terlibat kes cuci wang RM2.3 Juta. Pindahkan simpanan ke akaun audit negara untuk elak lokap.'",
    psychology: "Uses aggressive legal jargon and keeps victims on continuous long phone calls to prevent them from contacting family.",
    psychology_ms: "Menggunakan istilah undang-undang agresif dan memaksa mangsa terus berada dalam panggilan telefon yang panjang.",
    redFlags: ["Call transfer from multiple agencies", "Request transfer to 'Audit Account'"],
    redFlags_ms: ["Panggilan disambungkan ke pelbagai agensi", "Meminta pemindahan wang ke 'Akaun Audit'"],
    advisory: "PDRM and courts will NEVER demand money transfers into 'safe/audit accounts' over phone calls.",
    advisory_ms: "PDRM dan mahkamah TIDAK AKAN meminta pemindahan wang ke 'akaun selamat/audit' melalui panggilan telefon."
  },
  {
    id: 303,
    title: "JPJ Traffic Saman & License Suspension SMS",
    title_ms: "SMS Saman Trafik JPJ & Penggantungan Lesen",
    category: "Threat & Govt Impersonation",
    isDailyFeatured: false,
    summary: "Fake JPJ SMS claiming unpaid speed camera summons will result in immediate driving license revocation.",
    summary_ms: "SMS palsu JPJ mendakwa saman belum dibayar akan mengakibatkan pembatalan lesen memandu serta-merta.",
    exampleMessage: "JPJ NOTIS: Saman AES RM150 tertunggak. Lesen memandu akan digantung dalam 24 jam. Bayar segera di: jpj-saman-online.xyz",
    psychology: "Targets drivers' fear of license suspension using small fine amounts.",
    psychology_ms: "Menyasar ketakutan pemandu terhadap penggantungan lesen menggunakan jumlah denda yang kecil.",
    redFlags: ["Domains ending in .xyz or .club", "Claims license will be revoked automatically within 24 hours"],
    redFlags_ms: ["Domain berakhir dengan .xyz atau .club", "Mendakwa lesen ditarik balik dalam masa 24 jam"],
    advisory: "Always check and settle official traffic summonses via the official MyBayar PDRM or MySIKAP JPJ portals.",
    advisory_ms: "Sentiasa semak dan jelaskan saman trafik melalui portal rasmi MyBayar PDRM atau MySIKAP JPJ."
  },

  // --- Category 4: Impossible Investment ---
  {
    id: 401,
    title: "Telegram Syariah 1,000% Profit Multiplier",
    title_ms: "Pelaburan Syariah Telegram Untung 1,000%",
    category: "Impossible Investment",
    isDailyFeatured: false,
    summary: "Guarantees 1,000% returns in 3 hours. E.g. 'Invest RM1,000 and receive guaranteed reward payout of RM100,000'.",
    summary_ms: "Menjamin pulangan 1,000% dalam masa 3 jam. Cth. 'Labur RM1,000 dapat RM100,000'.",
    exampleMessage: "Peluang Pelaburan Syariah 100% Sah: Labur RM1,000 dapat pulangan RM100,000 dalam 3 jam! Dijamin 100% tanpa risiko. Hubungi Admin Telegram.",
    psychology: "Promises life-changing financial wealth with zero risk to entice financially stressed individuals.",
    psychology_ms: "Menjanjikan kekayaan pantas dengan sifar risiko untuk memikat individu yang tertekan kewangan.",
    redFlags: ["Guaranteed 1,000% profit in hours", "Claims 100% zero risk", "Conducted entirely inside Telegram private groups"],
    redFlags_ms: ["Jaminan untung 1,000% dalam beberapa jam", "Dakwa 100% sifar risiko", "Dijalankan sepenuhnya dalam Telegram"],
    advisory: "No legitimate investment can guarantee astronomical returns without risk. If it sounds too good to be true, it is 100% a scam.",
    advisory_ms: "Tiada pelaburan sah boleh menjamin pulangan yang terlalu besar tanpa risiko."
  },
  {
    id: 402,
    title: "Pre-IPO Stock Allocation Insider Scam",
    title_ms: "Scam Insider Peruntukan Saham Pra-IPO",
    category: "Impossible Investment",
    isDailyFeatured: false,
    summary: "Poses as a licensed investment broker offering guaranteed allocation of high-profile tech stocks before public listing.",
    summary_ms: "Menyamar sebagai broker berlesen yang menawarkan peruntukan dijamin bagi saham sebelum penyenaraian awam.",
    exampleMessage: "Bursa Insider Trading: Guaranteed allocation of 10,000 pre-IPO tech shares at 80% discount. Minimum investment RM2,000.",
    psychology: "Creates exclusivity and fear of missing out (FOMO) on major stock market profits.",
    psychology_ms: "Mencipta ilusi keistimewaan dan takut ketinggalan (FOMO) ke atas keuntungan pasaran saham yang besar.",
    redFlags: ["Claims access to illegal 'insider allocation'", "Requires sending funds to individual mule accounts"],
    redFlags_ms: ["Mendakwa mempunyai akses 'orang dalam' haram", "Meminta dana ke akaun baghal individu"],
    advisory: "Check the Securities Commission Malaysia (SC) Investor Alert List before investing in any financial scheme.",
    advisory_ms: "Sentiasa semak Senarai Makluman Pelabur Suruhanjaya Sekuriti Malaysia (SC) sebelum melabur."
  },
  {
    id: 403,
    title: "Automated Crypto Trading Bot Arbitrage Scam",
    title_ms: "Scam Bot Dagangan Kripto Automatik",
    category: "Impossible Investment",
    isDailyFeatured: false,
    summary: "Promises automated AI crypto trading bots yielding 5% daily compounding interest.",
    summary_ms: "Menjanjikan bot AI kripto automatik yang menghasilkan faedah kompaun 5% setiap hari.",
    exampleMessage: "CryptoAI Bot: Earn 5% daily profit automatically! Deposit 0.05 BTC to activate automated arbitrage trading engine.",
    psychology: "Uses modern buzzwords like 'AI Arbitrage Bot' to trick tech-enthusiasts into depositing cryptocurrency.",
    psychology_ms: "Menggunakan perkataan canggih seperti 'AI Bot' untuk menipu orang ramai mendeposit kripto.",
    redFlags: ["Guarantees daily positive yields in a volatile market"],
    redFlags_ms: ["Jaminan hasil positif setiap hari dalam pasaran tidak stabil"],
    advisory: "Unregulated crypto yield platforms carry extreme risks and frequently turn out to be Ponzi rug-pull schemes.",
    advisory_ms: "Platform hasil kripto tidak terkawal sering terbukti sebagai skim penipuan Ponzi (rug-pull)."
  },

  // --- Category 5: Emergency & Secrecy ---
  {
    id: 501,
    title: "Mum Phone Fell In Water Medical Bill Scam",
    title_ms: "Scam Kecemasan Fon Jatuh Air",
    category: "Emergency & Secrecy",
    isDailyFeatured: true,
    summary: "Posing as a child whose phone fell into water, asking for urgent money while strictly forbidding calling them.",
    summary_ms: "Menyamar sebagai anak yang telefonnya jatuh dalam air, meminta wang segera sambil melarang sama sekali panggilan telefon.",
    exampleMessage: "Mak, fon abang jatuh air. Ni nombor baru kawan. Tolong pindahkan RM1,000 segera ke akaun 164228910239 untuk repair. Jgn beritahu sesiapa & jgn telefon.",
    psychology: "Combines emotional panic for family safety with strict secrecy to prevent you from verifying with family members.",
    psychology_ms: "Menggabungkan panik emosi untuk keselamatan keluarga dengan larangan supaya anda tidak dapat mengesahkannya.",
    redFlags: ["Unverified new phone number", "Strictly forbids calling back ('speaker broken')", "Requests money transfer to unknown third-party account"],
    redFlags_ms: ["Nombor telefon baharu tidak disahkan", "Melarang panggilan ('fon rosak')", "Pindah wang ke akaun pihak ketiga"],
    advisory: "Always call your child/relative on their original phone number or verify through mutual family members before transferring money.",
    advisory_ms: "Sentiasa hubungi saudara pada nombor asal mereka atau sahkan melalui keluarga terdekat sebelum memindahkan wang."
  },
  {
    id: 502,
    title: "Fake Kidnapping & Ransom Phone Extortion",
    title_ms: "Peras Ugut Penculikan & Tebusan Palsu",
    category: "Emergency & Secrecy",
    isDailyFeatured: false,
    summary: "Scammer calls parents screaming in background, claiming their child has been kidnapped and demanding instant cash transfer.",
    summary_ms: "Pemanggil menjerit di latar belakang, mendakwa anak telah diculik dan menuntut pindahan wang tunai segera.",
    exampleMessage: "Phone call: 'Anak kamu ada dengan kami! Kami dah tangkap dia. Kalau nak dia selamat, kumpul RM20,000 sekarang & jangan hubungi polis!'",
    psychology: "Induces extreme emotional terror and confusion so parents comply before checking where their child actually is.",
    psychology_ms: "Menyebabkan keganasan emosi yang melampau supaya ibu bapa patuh sebelum menyemak di mana anak mereka.",
    redFlags: ["Calls from private/unknown numbers", "Refuses to let you speak directly to the child for verification"],
    redFlags_ms: ["Panggilan nombor tidak dikenali", "Enggan membenarkan anda bercakap secara terus dengan anak"],
    advisory: "Stay calm. Attempt to contact your child's school, workplace, or friends immediately while keeping the scammer on hold.",
    advisory_ms: "Bertenang. Cuba hubungi sekolah, tempat kerja, atau rakan anak anda dengan segera."
  },
  {
    id: 503,
    title: "Relative Arrested Police Bail Deposit Scam",
    title_ms: "Scam Deposit Jaminan Polis Saudara Ditahan",
    category: "Emergency & Secrecy",
    isDailyFeatured: false,
    summary: "Poses as a lawyer or police sergeant claiming a cousin/sibling was detained at a roadblock and needs urgent bail money.",
    summary_ms: "Menyamar sebagai peguam atau sarjan polis mendakwa saudara ditahan di sekatan jalan raya dan perlukan wang jaminan segera.",
    exampleMessage: "WhatsApp: 'Saya Sarjan Azman. Sepupu anda kini ditahan di balai kerana kesalahan dadah. Sila urus jaminan RM3,000 ke akaun peguam ini serta-merta.'",
    psychology: "Plays on family loyalty and urgency to bypass standard bail procedure verification.",
    psychology_ms: "Mempermainkan kesetiaan keluarga dan kecemasan untuk memintas prosedur pengesahan jaminan.",
    redFlags: ["Urgent police bail demanded via instant transfer to a civilian's account"],
    redFlags_ms: ["Deposit wang jaminan polis dituntut ke akaun orang awam"],
    advisory: "Bail payments in Malaysia are only processed physically at official court registries, never via instant bank transfers.",
    advisory_ms: "Pembayaran wang jaminan di Malaysia hanya diproses secara fizikal di pendaftaran mahkamah rasmi, bukan pindahan segera."
  },

  // --- Category 6: Quishing / QR Code Scams ---
  {
    id: 601,
    title: "Hawker Stall QR Sticker Swap Payment Scam",
    title_ms: "Scam Pelekat Kod QR Gerai Penjaja",
    category: "Quishing / QR Code",
    isDailyFeatured: false,
    summary: "Scammers secretly paste malicious QR code stickers over authentic hawker stall payment signs, stealing customer payments.",
    summary_ms: "Penipu menampal pelekat kod QR di atas tanda pembayaran gerai yang sah untuk mencuri pembayaran pelanggan.",
    exampleMessage: "Scanned QR Code Target: https://maybank-secure-pay.xyz/merchant/transfer-funds?amount=15.00",
    psychology: "Relies on customer habits of quickly scanning QR codes without checking the business merchant name on the payment screen.",
    psychology_ms: "Bergantung pada tabiat pengguna yang pantas mengimbas tanpa menyemak nama pedagang.",
    redFlags: ["QR code is a physical sticker pasted over an original sign", "Payment screen shows an individual's name instead of stall name"],
    redFlags_ms: ["Pelekat kod QR fizikal ditampal di atas papan asal", "Skrin pembayaran menunjukkan nama individu bukan nama kedai"],
    advisory: "Always verify the merchant's business name on your e-wallet payment confirmation screen before entering your PIN.",
    advisory_ms: "Sentiasa sahkan nama perniagaan saudagar pada skrin pengesahan pembayaran dompet e-mel anda sebelum memasukkan PIN."
  },
  {
    id: 602,
    title: "Parking Kiosk Fake Touch 'n Go QR Code",
    title_ms: "Kod QR Palsu Mesin Letak Kereta",
    category: "Quishing / QR Code",
    isDailyFeatured: false,
    summary: "Fake QR stickers pasted on street parking meters leading to phishing portals that harvest credit card numbers.",
    summary_ms: "Pelekat QR palsu ditampal pada mesin parkir membawa kepada portal pancingan data untuk curi kad kredit.",
    exampleMessage: "Scanned QR Target: https://tng-parking-pay.club/kiosk/kl-zone-1",
    psychology: "Targets drivers in a hurry trying to avoid getting a parking fine.",
    psychology_ms: "Menyasar pemandu yang tergesa-gesa cuba mengelak denda parkir.",
    redFlags: ["Points to non-official URLs (.club or .info)", "Asks for full credit card details instead of e-wallet integration"],
    redFlags_ms: ["URL tidak rasmi (.club / .info)", "Minta butiran kad kredit penuh dan bukan dompet e-mel"],
    advisory: "Only pay parking using official council apps (e.g. Flexi Parking, Touch 'n Go eWallet) directly.",
    advisory_ms: "Hanya bayar parkir menggunakan aplikasi majlis perbandaran rasmi (cth. Flexi Parking, TnG eWallet)."
  },
  {
    id: 603,
    title: "Event Poster Free Voucher QR Malware Scam",
    title_ms: "Scam Malware Baucar Percuma Kod QR Poster",
    category: "Quishing / QR Code",
    isDailyFeatured: false,
    summary: "Promotional posters in shopping malls promising free RM50 shopping vouchers via QR code scan, installing malicious APKs.",
    summary_ms: "Poster promosi menjanjikan baucar beli-belah percuma melalui imbasan QR, memasang aplikasi hasad APK.",
    exampleMessage: "Scanned QR Target: https://shopee-voucher-claim.info/download/ShopeeBonus.apk",
    psychology: "Entices users with free gifts to trick them into installing dangerous Android malware apps.",
    psychology_ms: "Memikat pengguna dengan hadiah percuma untuk menipu mereka supaya memasang malware Android yang berbahaya.",
    redFlags: ["Prompts downloading an .APK file directly", "Requests Android Accessibility and SMS permissions"],
    redFlags_ms: ["Meminta untuk muat turun fail .APK terus", "Meminta kebenaran Aksesibiliti Android dan SMS"],
    advisory: "Never install .APK software files downloaded from unknown QR code scans.",
    advisory_ms: "Jangan sesekali memasang perisian fail .APK yang dimuat turun daripada imbasan kod QR tidak dikenali."
  }
];
